name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bookworm-slim

    steps:
    - uses: actions/checkout@v4

    - name: install deps
      run: apt-get update && apt-get install -y cmake pkg-config libuv1-dev libcurl4-openssl-dev libsqlite3-dev libssl-dev libcjson-dev check

    - name: configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

    - name: build
      run: cmake --build build

    - name: test
      run: ctest --test-dir build -V
